require 'forwardable'
require 'active_support'
require 'active_support/core_ext/hash/indifferent_access'
require 'active_support/core_ext/class/attribute'
require 'active_support/concern'
require 'active_support/hash_with_indifferent_access'
require 'active_model/serialization'
require 'active_model/naming'
require 'active_model/serializers/json'
require 'dooly/version'
require 'dooly/attachment'
require 'dooly/attachment/base'
require 'dooly/collection'
require 'dooly/collection/base'
require 'dooly/id_proxy'
require 'dooly/id_proxy/base'
require 'dooly/model_regulator'

module Dooly
end